export const VIDEO_SEARCH_PRESET_ERROR_CODES = {
  NOT_FOUND: "VIDEO_SEARCH_PRESET_NOT_FOUND",
  LIMIT_EXCEEDED: "VIDEO_SEARCH_PRESET_LIMIT_EXCEEDED",
  DUPLICATE_NAME: "VIDEO_SEARCH_PRESET_DUPLICATE_NAME",
  CREATE_FAILED: "VIDEO_SEARCH_PRESET_CREATE_FAILED",
  DELETE_FAILED: "VIDEO_SEARCH_PRESET_DELETE_FAILED",
  GET_FAILED: "VIDEO_SEARCH_PRESET_GET_FAILED"
} as const

export type VideoSearchPresetErrorCode =
  (typeof VIDEO_SEARCH_PRESET_ERROR_CODES)[keyof typeof VIDEO_SEARCH_PRESET_ERROR_CODES]
