export const YOUTUBE_RESEARCH_ERROR_CODES = {
  API_REQUEST_FAILED: "YOUTUBE_API_REQUEST_FAILED",
  SEARCH_FAILED: "YOUTUBE_SEARCH_FAILED",
  GET_CATEGORIES_FAILED: "YOUTUBE_GET_CATEGORIES_FAILED"
} as const

export type YouTubeResearchErrorCode =
  (typeof YOUTUBE_RESEARCH_ERROR_CODES)[keyof typeof YOUTUBE_RESEARCH_ERROR_CODES]
